apiVersion: 1

contactPoints:
  - orgId: 1
    name: alertmanager
    receivers:
      - uid: am_default
        type: prometheus-alertmanager
        disableResolveMessage: false
        settings:
          url: http://alertmanager:9093

policies:
  - orgId: 1
    receiver: alertmanager
    group_by:
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
