#!/usr/bin/env python3
"""Regenerate ops/BOARD.md from ticket frontmatter. Vault-relative links."""
from __future__ import annotations

import os
import pathlib

COLUMNS = [
    ("inbox", "Inbox"),
    ("ready", "Ready"),
    ("plan", "Plan"),
    ("implement", "Implement"),
    ("review", "Review"),
    ("blocked", "Blocked"),
    ("done", "Done"),
]

PRIORITY_RANK = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}


def root() -> pathlib.Path:
    env = os.environ.get("OPS_ROOT")
    if env:
        return pathlib.Path(env)
    return pathlib.Path(__file__).resolve().parents[1]


def parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[4:end]
    data: dict[str, str] = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        data[key.strip()] = val.strip().strip('"').strip("'")
    return data


def load_tickets(tickets_dir: pathlib.Path | None = None) -> list[dict[str, str]]:
    tickets_dir = tickets_dir or (root() / "tickets")
    rows = []
    for path in sorted(tickets_dir.glob("*.md")):
        if path.name.startswith("_"):
            continue
        meta = parse_frontmatter(path.read_text())
        if not meta.get("id"):
            continue
        meta["file"] = path.stem
        rows.append(meta)
    rows.sort(
        key=lambda r: (
            PRIORITY_RANK.get(r.get("priority", "P2"), 9),
            r.get("id", ""),
        )
    )
    return rows


def render_board(tickets: list[dict[str, str]]) -> str:
    by_status: dict[str, list[dict[str, str]]] = {k: [] for k, _ in COLUMNS}
    for t in tickets:
        status = t.get("status", "inbox")
        if status not in by_status:
            status = "inbox"
        by_status[status].append(t)

    lines = [
        "---",
        "kanban-plugin: basic",
        "---",
        "",
        "> Generated by `python3 ops/scripts/board_sync.py`. Edit tickets, not this file.",
        "",
    ]
    for key, title in COLUMNS:
        lines.append(f"## {title}")
        lines.append("")
        for t in by_status[key]:
            ident = t["id"]
            title_text = t.get("title") or ident
            pri = t.get("priority", "")
            lines.append(
                f"- [ ] [[tickets/{ident}|{ident}]] {pri} {title_text}".rstrip()
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_board(ops_root: pathlib.Path | None = None) -> pathlib.Path:
    ops_root = ops_root or root()
    tickets = load_tickets(ops_root / "tickets")
    board = ops_root / "BOARD.md"
    board.write_text(render_board(tickets))
    return board


def main() -> None:
    ops_root = root()
    board = write_board(ops_root)
    tickets = load_tickets(ops_root / "tickets")
    print(f"wrote {board.relative_to(ops_root.parent)} ({len(tickets)} tickets)")


if __name__ == "__main__":
    main()
